package thelm.jaopca.additions;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import thelm.jaopca.additions.modules.RegistryAdditions;

@Mod(
		modid = JAOPCAAdditions.MOD_ID,
		name = "JAOPCAAdditions",
		version = JAOPCAAdditions.VERSION,
		dependencies = "required-before:jaopca@[1.11.2-1.1.12,)"
		)
public class JAOPCAAdditions {
	public static final String MOD_ID = "jaopcaadditions";
	public static final String VERSION = "1.11.2-1.1.1";
	@Instance(JAOPCAAdditions.MOD_ID)
	public static JAOPCAAdditions core;
	public static ModMetadata metadata;

	@EventHandler
	public void firstMovement(FMLPreInitializationEvent event) {
		metadata = event.getModMetadata();
		metadata.autogenerated = false;
		metadata.modId = MOD_ID;
		metadata.version = VERSION;
		metadata.name = "Just A Ore Processing Compatibility Attempt: Additions";
		metadata.credits = "Idea taken from Substratum";
		metadata.authorList.add("TheLMiffy1111");
		metadata.description = "A mod that aims to add common materials for ores.";

		RegistryAdditions.preInit();
	}
}
